### PR TITLE
Fix group edit

### LINKED ISSUE #443: [Code review] @lelerer
1.  You can leave out comments if it is self-explanatory. See [explain the what, why and not how](https://nus-cs2113-ay2122s2.github.io/website/se-book-adapted/chapters/codeQuality.html#explain-what-and-why-not-how).

Screenshot 2022-04-05 at 11 15 31 AM

Otherwise, include _what_ the code is supposed to do - e.g. Formats the group description as group's id, name etc.. 
Screenshot 2022-04-05 at 11 15 02 AM

2. There are 4 blocks of try catch code that is catching an `InvalidFormatException`. This is [repetitive code](https://nus-cs2113-ay2122s2.github.io/website/se-book-adapted/chapters/codeQuality.html#minimise-code-duplication).
How about using a single try catch block? Hint: if else statements to create new error messages in single catch block where possible.
Screenshot 2022-04-05 at 11 17 47 AM

### PR DESCRIPTION
**Pull request by lelerer**
Update GroupEditCommand class to check for:
1. The new person list cannot be exactly the same as the old list.
2. The new group name must not be the same as the old group name.

Fixes #443

### CODE REVIEW

File: src/main/java/seedu/splitlah/command/GroupEditCommand.java [hunk 1]
```diff
@@ -36,6 +36,34 @@ public GroupEditCommand(String[] involvedList, String groupName, int groupId) {
...
+                return isSame;
+            }
+        }
+        if (newList.getSize() != oldList.size()) {
+            isSame = false;
+        }
+        return isSame;
+    }
+    
+    public boolean existingGroupWithTheSameName(Manager manager, String newName, int groupId) {
```
Comment (froststein) [inline src/main/java/seedu/splitlah/command/GroupEditCommand.java:56]: Perhaps parsing in the group list itself, instead of manager

**Review by froststein — CHANGES_REQUESTED** [review]
Requested change for method signature.

File: src/main/java/seedu/splitlah/ui/Message.java [hunk 2]
```diff
@@ -448,6 +448,14 @@
     // Group Edit Command
     public static final String ASSERT_GROUPEDIT_GROUP_ID_INVALID =
             "Group ID is less than or equals to zero.";
+    public static final String ERROR_GROUPEDIT_SAME_PERSON_LIST =
+            "The new person list is the same as old list"
+                  + " ,please rectify and try again.";
```
Comment (ivanaitzliddat) [inline src/main/java/seedu/splitlah/ui/Message.java:453]: Perhaps can shift the comma to the first String

File: src/main/java/seedu/splitlah/command/GroupEditCommand.java [hunk 3]
```diff
@@ -15,9 +17,7 @@
  * @author Tianle
  */
 public class GroupEditCommand extends Command {
-
     private static final String COMMAND_SUCCESS = "The group was edited successfully.\n";
```
Comment (ivanaitzliddat) [inline src/main/java/seedu/splitlah/command/GroupEditCommand.java:20]: Possible to remove extra \n to prevent printing additional new line

File: src/main/java/seedu/splitlah/command/GroupEditCommand.java [hunk 4]
```diff
@@ -60,11 +88,28 @@ public void run(Manager manager) {
...
-            group.setGroupName(groupName);
+            if (groupName.equals(group.getGroupName())) {
+                ui.printlnMessage(Message.ERROR_GROUPEDIT_GROUP_NAME_NOT_NEW);
+                return;
+            } else if (existingGroupWithTheSameName(manager.getProfile().getGroupList(), groupName, groupId)) {
+                ui.printlnMessage(Message.ERROR_GROUPEDIT_GROUP_NAME_DUPLICATE);
+                return;
+            } else {
+                group.setGroupName(groupName);
+            }
```
Comment (ivanaitzliddat) [inline src/main/java/seedu/splitlah/command/GroupEditCommand.java:112]: Perhaps, can change the logic here to make sure that the logic is as such:

- check if same person list
- check if same name
- if same name and same person list —> print error and return
- else update whichever is changed

**Review by ivanaitzliddat — CHANGES_REQUESTED** [review]
I think the logic flow is a little wrong, please kindly edit it

**Review by froststein — APPROVED** [review]
Looks good to merge

**Review by froststein — CHANGES_REQUESTED** [review]
Generally looks alright. There are some changes to be made .

**Review by froststein — APPROVED** [review]
Looks good to merge

**Review by ivanaitzliddat — APPROVED** [review]
Looks good to merge
