### PR TITLE
Remove error checking from ActivityCost

### LINKED ISSUE #57: Remove error checking from constructors in ActivityCost
Parser should handle invalid input, so there is no need for ActivityCost constructors to throw exceptions.

### PR DESCRIPTION
**Pull request by matheril**
ActivityCost no longer checks for invalid input or throws exceptions.
The Parser should handle invalid input
Fixes #57

### CODE REVIEW

File: src/main/java/seedu/duke/data/ActivityCost.java [hunk 1]
```diff
@@ -33,9 +24,8 @@ public ActivityCost(int activityId, double cost) throws InvalidDataException {
      * Constructs an ActivityCost object and sets cost to 0 if only activityId is supplied.
      * Assumption: Every field is non-negative.
      * @param activityId int representing the activityId.
```
Comment (froststein) [inline src/main/java/seedu/duke/data/ActivityCost.java:26]: Consider line break between for the javadocs.

**Review by froststein — CHANGES_REQUESTED** [review]
Over all looks good, just need to amend the javadocs

**Review by froststein — APPROVED** [review]
