### PR TITLE
Bug Fixes for PED

### LINKED ISSUE #406: [PE-D] Null Pointer Exception when trying to delete existing group
After adding a group and viewing that the group exists in the database, deleting the same group using the `group /delete /sid` command results to the app crashing due to NullPointerException.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shxr3f/ped#1

### LINKED ISSUE #409: [PE-D] Allow same edits
Able to edit to the same name again. Consider not allowing edits when the edit command did not change anything

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: FaliciaOng/ped#2

### LINKED ISSUE #410: [PE-D] Session name not unique across all active session after editing
When creating the session, sessions with unique names could be created. However, after running session /edit and editing a name of the session to a existing session, the execution is possible. Thus, now, sessions with unique names are not unique anymore as shown in the screenshot below:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Musfirahe0556596/ped#1

### LINKED ISSUE #422: [PE-D] Alphanumeric characters cannot be used to idetify persons
UG says i can use alphanumeric characters but when I try to create a session with participant names that have numbers it does not show up.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: shxr3f/ped#6

### PR DESCRIPTION
**Pull request by froststein**
Fixes #410
Added more layers of checks to ensure that if any fields contains invalid arguments, session is not edited.

Fixes #406
Added an additional layer of checking to ensure that the group retrieved is not null when trying to remove.

Fixes #422
Added an additional layer of checking to check if supplied person list has any invalid names. If any names were considered to be invalid, the session would not be created and an error message will be printed.

Fixes #409
Added additional checks to see if session was edited. If any of the editable fields in the command was found to be edited, a success edit message is sent. If all the supplied arguments contain the same information as before, a "no edits has been made" will be printed.

### CODE REVIEW

File: src/main/java/seedu/splitlah/command/SessionCreateCommand.java [hunk 1]
```diff
@@ -80,6 +85,8 @@ public void run(Manager manager) {
             }
         }
 
+
+
```
Comment (warrencxw) [inline src/main/java/seedu/splitlah/command/SessionCreateCommand.java:89]: Consider removing these unnecessary new lines for standardisation.

File: src/main/java/seedu/splitlah/command/SessionEditCommand.java [hunk 2]
```diff
@@ -19,6 +20,8 @@
 public class SessionEditCommand extends Command {
 
     private static final String COMMAND_SUCCESS = "The session was edited successfully.";
+    private static final String COMMAND_NO_EDITS_MADE = "The session was not edited.";
+
```
Comment (warrencxw) [inline src/main/java/seedu/splitlah/command/SessionEditCommand.java:24]: Consider removing one extra new line for standardisation

File: src/main/java/seedu/splitlah/command/SessionEditCommand.java [hunk 3]
```diff
@@ -49,41 +52,68 @@ public SessionEditCommand(int sessionId, String sessionName, String[] personName
...
                 ui.printlnMessageWithDivider(Message.ERROR_SESSIONEDIT_INVALID_PERSONLIST);
                 return;
-            } else {
-                for (Person person : newPersonList.getPersonList()) {
-                    session.addPerson(person);
-                }
+            }
+            if (!(newPersonList.isSuperset(session.getPersonArrayList())
+                    && session.getPersonList().isSuperset(newPersonList.getPersonList()))) {
+                isPersonNamesEdited = true;
```
Comment (warrencxw) [inline src/main/java/seedu/splitlah/command/SessionEditCommand.java:81]: You can omit one check here (`newPersonList.isSuperset(session.getPersonArrayList())` returns true at this line) as you have already performed that check earlier.

File: src/main/java/seedu/splitlah/ui/Message.java [hunk 4]
```diff
@@ -174,6 +177,9 @@
     public static final String LOGGER_PERSONLIST_NAME_DUPLICATE_EXISTS_IN_CREATESESSION =
             "An Session object failed to be added into the list of sessions because there are duplicate names in"
                     + "the person list.";
+    public static final String LOGGER_PERSONLIST_INVALID_NAME_EXISTS_IN_CREATESESSION =
+            "An Session object failed to be added into the list of sessions because there are names in"
+                    + "the person list.";
```
Comment (warrencxw) [inline src/main/java/seedu/splitlah/ui/Message.java:182]: I think something is wrong with this sentence, might need to rephrase here.

**Review by warrencxw — APPROVED** [review]
Generally looks okay, but can make minor changes to improve code quality.

**Review by warrencxw — APPROVED** [review]
Looks good to merge.
